dontChroot: false
timeout: 600
script:
  - "rm -f /etc/resolv.conf"
  - "sh -c 'echo nameserver 1.1.1.1 > /etc/resolv.conf; echo nameserver 8.8.8.8 >> /etc/resolv.conf'"
  - "sed -i 's/^HOOKS=.*/HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck)/' /etc/mkinitcpio.conf"
  - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
  - "rm -f /etc/mkinitcpio.d/linux.preset"
  - "pacman-key --init"
  - "pacman-key --populate archlinux"
  - "pacman -Sy --noconfirm linux"
  - "mkinitcpio -P"