---
dontChroot: false
timeout: 10
script:
    - "-rm -f /etc/sddm.conf.d/autologin.conf"
    - "-rm -f /etc/skel/Desktop/calamares.desktop"
    - "-rm -f /etc/skel/Рабочий\\ стол/calamares.desktop"
    - "-rm -rf /home/liveuser"
    - "find /home/ -type f -name 'calamares.desktop' -delete"